spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    url: jdbc:mysql://localhost:3306/loginregister?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/sqlMapper/*.xml

server:
  port: 9090